name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64
          cc: 1

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Build and test
        run: |
          conan create $GITHUB_WORKSPACE yuki/devel -pr:h $GITHUB_WORKSPACE/conan/clang_profile -pr:b $GITHUB_WORKSPACE/conan/clang_profile

      - name: Setup Conan user
        run: |
          conan remote add yukicpp https://yukicpp.jfrog.io/artifactory/api/conan/conan-yuki
          conan user -p ${{ secrets.ARTIFACTORY_KEY }} -r yukicpp yuki-bot

      - name: Upload to Artifactory
        if: github.event.pull_request.merged == true
        run: |
          echo HERE
          # conan upload "*@yuki/devel" -r=yukicpp --all -c --skip-upload