name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: yukicpp.jfrog.io/ci-images/ubuntu_20_04:clang-13
      credentials:
        username: yuki-bot
        password: ${{ secrets.DOCKER_PWD }}

    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: |
          conan create $GITHUB_WORKSPACE yuki/devel -pr:h $GITHUB_WORKSPACE/conan/clang_profile -pr:b $GITHUB_WORKSPACE/conan/clang_profile

      - name: Setup Conan user
        run: |
          conan remote add yukicpp https://yukicpp.jfrog.io/artifactory/api/conan/conan-yuki
          conan user -p ${{ secrets.DOCKER_PWD }} -r yukicpp yuki-bot

      - name: Upload to Artifactory
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo "Will update on artifactory when ready"
          # conan upload "*@yuki/devel" -r=yukicpp --all -c --skip-upload