name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
          cc: 1

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          conan profile new clang
          conan profile update settings.os=Linux
          conan profile update settings.os_build=Linux
          conan profile update settings.arch=x86_64
          conan profile update settings.arch_build=x86_64
          conan profile update settings.compiler=clang
          conan profile update settings.compiler.version=13
          conan profile update settings.compiler.libcxx=libstdc++11
          conan profile update settings.build_type=Release