name: Build and Test Package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yuki-cpp/ubuntu_20_04:clang-13
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build and test
        run: |
          vcpkg integrate install
          mkdir build
          cmake -S $GITHUB_WORKSPACE -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_TOOLCHAIN
          sonar-build-wrapper --out-dir sonar_out cmake --build build/
          ./build/bin/typelist_utils -r sonarqube > ./build/test_results.xml
          llvm-profdata-13 merge -sparse ./default.profraw -o ./default.profdata
          llvm-cov-13 show ./build/bin/typelist_utils -instr-profile=./default.profdata --format=text > ./build/coverage.txt


      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.host.url="https://sonarcloud.io" --define sonar.cfamily.build-wrapper-output="sonar_out"